# Configuration du projet de test Creedengo Flutter
sonar.projectKey=flutter-test-creedengo
sonar.projectName=Flutter Test Creedengo
sonar.projectVersion=1.0

# Chemins source
sonar.sources=lib
sonar.language=dart

# Encodage
sonar.sourceEncoding=UTF-8

# Exclusions (optionnel)
sonar.exclusions=**/*.g.dart,**/*.freezed.dart
